#!/bin/bash
echo About to promote to live

# Stash away the directory with the source in it
SOURCE_DIR=`pwd`

# Push from the integration repo to GitHub
cd $1
git push origin master

# Back to the source
cd $SOURCE_DIR

# Push to localhost
fab -H root@127.0.0.1:64111 deploy

echo Promoted, all done.